name: release

# on:
#   release:
#     types: [created]

on:
  push:
    tags:
      - "*"

jobs:
  releases-matrix:
    name: Release Go binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goos: [linux, windows, darwin, freebsd]
        goarch: ["386", amd64]
        # goarch: ["386", amd64, arm, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          # - goarch: arm
          #   goos: windows

    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.17
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          project_path: "./cmd/icanhasrobots"
          binary_name: "icanhasrobots"
          extra_files: LICENSE README.md
